from pathlib import Path
import re

# Panel-configured per-image minimum disk is authoritative for LXC.
Path('panel/app/services/image_policy.py').write_text('''from __future__ import annotations\n\nfrom dataclasses import dataclass\n\nDEFAULT_IMAGE_MIN_DISK_GB = 1.0\nKVM_MIN_DISK_GB = 3.0\n\nclass ImagePolicyError(ValueError):\n    pass\n\n@dataclass(frozen=True)\nclass ImageRequirement:\n    min_disk_gb: float\n    reason: str\n\ndef minimum_disk_for_alias(alias: str, family: str = "", virtualization_type: str = "lxc") -> ImageRequirement:\n    mode = str(virtualization_type or "lxc").strip().lower()\n    required = KVM_MIN_DISK_GB if mode == "kvm" else DEFAULT_IMAGE_MIN_DISK_GB\n    return ImageRequirement(required, "KVM 全局最低系统盘" if mode == "kvm" else "系统镜像后台配置")\n\ndef image_min_disk_gb(image, virtualization_type: str = "lxc") -> float:\n    configured = max(float(getattr(image, "min_disk_gb", 0) or DEFAULT_IMAGE_MIN_DISK_GB), 0.125)\n    if str(virtualization_type or "lxc").strip().lower() == "kvm":\n        return max(configured, KVM_MIN_DISK_GB)\n    return configured\n\ndef validate_image_resources(image, disk_gb: float, virtualization_type: str = "lxc") -> None:\n    required = image_min_disk_gb(image, virtualization_type)\n    current = float(disk_gb or 0)\n    if current + 1e-9 < required:\n        name = str(getattr(image, "name", None) or getattr(image, "alias", None) or "该系统镜像")\n        raise ImagePolicyError(f"{name} 最低需要 {required:g} GiB 系统盘，当前配置为 {current:g} GiB。")\n''')

p=Path('panel/app/models.py'); s=p.read_text(); old='min_disk_gb: Mapped[float] = mapped_column(Float, default=2.0)'; assert old in s; p.write_text(s.replace(old,'min_disk_gb: Mapped[float] = mapped_column(Float, default=1.0)',1))

p=Path('panel/app/schema.py'); s=p.read_text(); s=s.replace('"min_disk_gb": "FLOAT NOT NULL DEFAULT 2.0"','"min_disk_gb": "FLOAT NOT NULL DEFAULT 1.0"',1)
start=s.index('        if "system_images" in existing_tables:')
end=s.index('        # Existing traffic-reset migration behavior.', start)
new='''        if "system_images" in existing_tables:\n            image_columns = {row["name"] for row in inspect(conn).get_columns("system_images")}\n            if "min_disk_gb" in image_columns:\n                conn.execute(text('UPDATE "system_images" SET "min_disk_gb" = 1.0 WHERE COALESCE("min_disk_gb", 0) <= 0'))\n                if "site_settings" in existing_tables:\n                    marker = conn.execute(text("SELECT value FROM site_settings WHERE key='image_disk_policy_configurable_v1'")).scalar_one_or_none()\n                    if marker is None:\n                        result = conn.execute(text('UPDATE "system_images" SET "min_disk_gb" = 1.0 WHERE LOWER("alias") LIKE \'images:debian/%\' AND ABS(COALESCE("min_disk_gb", 0) - 2.0) < 0.000001'))\n                        conn.execute(text("INSERT INTO site_settings (key, value) VALUES ('image_disk_policy_configurable_v1', 'done')"))\n                        if (result.rowcount or 0) > 0:\n                            changed.append(f"system_images.min_disk_gb.debian_backfill={result.rowcount}")\n\n'''
s=s[:start]+new+s[end:]; p.write_text(s)

p=Path('panel/app/main.py'); s=p.read_text(); s=s.replace('from .services.image_policy import ImagePolicyError, minimum_disk_for_alias, validate_image_resources','from .services.image_policy import ImagePolicyError, validate_image_resources')
s=s.replace('SystemImage(name="Debian 12", alias="images:debian/12", family="apt", min_disk_gb=2.0, sort_order=10)','SystemImage(name="Debian 12", alias="images:debian/12", family="apt", min_disk_gb=1.0, sort_order=10)')
s=s.replace('SystemImage(name="Debian 13", alias="images:debian/13", family="apt", min_disk_gb=2.0, sort_order=20)','SystemImage(name="Debian 13", alias="images:debian/13", family="apt", min_disk_gb=1.0, sort_order=20)')
pattern=r'@app\.post\("/admin/system-images"\)\ndef admin_add_system_image\(.*?(?=\n\n@app\.post\("/admin/system-images/\{image_id\}/toggle"\))'; m=re.search(pattern,s,re.S); assert m
replacement='''@app.post("/admin/system-images")\ndef admin_add_system_image(request:Request,name:str=Form(...),alias:str=Form(...),min_disk_gb:float=Form(1.0),csrf_token:str=Form(...)):\n    validate_csrf(request,csrf_token); name=name.strip(); alias=alias.strip()\n    if not name or not alias.startswith("images:"):\n        flash(request,"名称不能为空，镜像别名必须以 images: 开头。","error"); return RedirectResponse("/admin?section=images",status_code=303)\n    if min_disk_gb < 0.125 or min_disk_gb > 1024:\n        flash(request,"最低系统盘必须在 0.125 GiB 到 1024 GiB 之间。","error"); return RedirectResponse("/admin?section=images",status_code=303)\n    with db_session() as db:\n        admin=admin_required(request,db)\n        if db.scalar(select(SystemImage).where(or_(SystemImage.name==name,SystemImage.alias==alias))):\n            flash(request,"系统名称或镜像别名已经存在。","error"); return RedirectResponse("/admin?section=images",status_code=303)\n        family="alpine" if alias.lower().startswith("images:alpine/") else "apt"\n        row=SystemImage(name=name,alias=alias,family=family,min_disk_gb=float(min_disk_gb),is_active=True,sort_order=100)\n        db.add(row); db.flush(); write_audit(db,actor=admin,request=request,action="admin.image.create",target_type="system_image",target_id=row.id,target_name=row.name,detail={"alias":row.alias,"min_disk_gb":row.min_disk_gb}); db.commit(); flash(request,f"系统镜像 {name} 已添加。","success")\n    return RedirectResponse("/admin?section=images",status_code=303)\n\n@app.post("/admin/system-images/{image_id}/disk")\ndef admin_update_system_image_disk(request:Request,image_id:int,min_disk_gb:float=Form(...),csrf_token:str=Form(...)):\n    validate_csrf(request,csrf_token)\n    if min_disk_gb < 0.125 or min_disk_gb > 1024:\n        flash(request,"最低系统盘必须在 0.125 GiB 到 1024 GiB 之间。","error"); return RedirectResponse("/admin?section=images",status_code=303)\n    with db_session() as db:\n        admin=admin_required(request,db); row=db.get(SystemImage,image_id)\n        if not row: raise HTTPException(404,"系统镜像不存在")\n        before=float(row.min_disk_gb or 0); row.min_disk_gb=float(min_disk_gb); write_audit(db,actor=admin,request=request,action="admin.image.disk.update",target_type="system_image",target_id=row.id,target_name=row.name,detail={"before":before,"after":row.min_disk_gb}); db.commit(); flash(request,f"{row.name} 最低系统盘已更新为 {row.min_disk_gb:g} GiB。","success")\n    return RedirectResponse("/admin?section=images",status_code=303)'''
s=s[:m.start()]+replacement+s[m.end():]; p.write_text(s)

p=Path('panel/app/templates/admin.html'); s=p.read_text(); s=s.replace('<thead><tr><th>ID</th><th>名称</th><th>Incus 镜像</th><th>状态</th><th>操作</th></tr></thead>','<thead><tr><th>ID</th><th>名称</th><th>Incus 镜像</th><th>最低系统盘</th><th>状态</th><th>操作</th></tr></thead>',1)
old='          <td><code>{{ image.alias }}</code></td>\n          <td>{{ "启用" if image.is_active else "停用" }}</td>'; assert old in s
new='''          <td><code>{{ image.alias }}</code></td>\n          <td><form method="post" action="/admin/system-images/{{ image.id }}/disk" class="inline-form"><input type="hidden" name="csrf_token" value="{{ csrf_token }}"><input type="number" name="min_disk_gb" min="0.125" max="1024" step="0.125" value="{{ image.min_disk_gb }}" style="width:92px" required><button type="submit">保存</button></form></td>\n          <td>{{ "启用" if image.is_active else "停用" }}</td>'''; s=s.replace(old,new,1)
old='<label>Incus 镜像别名<input name="alias" placeholder="images:debian/14" required></label>\n        <button type="submit">添加系统</button>'; assert old in s; s=s.replace(old,'<label>Incus 镜像别名<input name="alias" placeholder="images:debian/14" required></label>\n        <label>最低系统盘 (GiB)<input type="number" name="min_disk_gb" min="0.125" max="1024" step="0.125" value="1" required></label>\n        <button type="submit">添加系统</button>',1); p.write_text(s)

p=Path('panel/app/mobile_api.py'); s=p.read_text(); old='{"id": row.id, "name": row.name, "alias": row.alias, "family": row.family}'; assert old in s; p.write_text(s.replace(old,'{"id": row.id, "name": row.name, "alias": row.alias, "family": row.family, "min_disk_gb": float(row.min_disk_gb or 1.0)}',1))

p=Path('docs/MOBILE_API.md'); s=p.read_text(); marker='- `GET /api/v1/system-images`\n';
if marker in s and '系统镜像 payload 包含 `min_disk_gb`' not in s: s=s.replace(marker,marker+'\n系统镜像 payload 包含 `min_disk_gb`，表示 Panel 后台为该镜像配置的最低系统盘（GiB）。LXC 直接使用该值；KVM 还会应用服务端 3 GiB 全局底线。\n',1)
p.write_text(s)
